shfmt

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,6 +1,9 @@
 #!/bin/sh
-set -e
-
+set -o errexit          # Exit on most errors (see the manual)
+set -o errtrace         # Make sure any error trap is inherited
+set -o nounset          # Disallow expansion of unset variables
+set -o pipefail         # Use last non-zero exit code in a pipeline
+#set -o xtrace          # Trace the execution of the script (debug)
 export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 # shellcheck disable=SC2154
@@ -9,7 +12,7 @@ trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
 BREW_PREFIX="/usr/local"
 BREW_INSTALLER="https://raw.githubusercontent.com/Homebrew/install/master/install"
 
-run_setup () {
+run_setup() {
   SECONDS=0
   request_root_privileges
   setup_xcode
@@ -17,33 +20,34 @@ run_setup () {
   install_formulaes_from_brewfile
 
   # shellcheck disable=SC2039
-  echo "✨  Done in $(($SECONDS))s."
+  echo "✨  Done in $((SECONDS))s."
   exit 0
 }
 
-log () {
-  message="$1"; shift
+log() {
+  message="$1"
+  shift
   # shellcheck disable=SC2059
   printf "$message\n" "$@"
 }
 
-get_dotfiles_path () {
+get_dotfiles_path() {
   fp="$(readlink -f ${0})"
   dir=$(dirname $fp)
   cd $dir || exit 1
   echo "$(git rev-parse --show-toplevel)"
 }
 
-get_brewfile_path () {
+get_brewfile_path() {
   echo "$(get_dotfiles_path)/Brewfile"
 }
 
-install_formulaes_from_brewfile () {
+install_formulaes_from_brewfile() {
   brew update --force
   brew bundle --file="$(get_brewfile_path)"
 }
 
-is_xcode_command_line_tools_installed () {
+is_xcode_command_line_tools_installed() {
   if xcode-select -p > /dev/null; then
     return 0
   else
@@ -51,14 +55,14 @@ is_xcode_command_line_tools_installed () {
   fi
 }
 
-install_xcode_command_line_tools () {
+install_xcode_command_line_tools() {
   xcode-select --install > /dev/null
   until xcode-select -p > /dev/null; do
     sleep 5
   done
 }
 
-is_xcode_eula_accepted () {
+is_xcode_eula_accepted() {
   if sudo xcodebuild -license status; then
     return 0
   else
@@ -66,11 +70,11 @@ is_xcode_eula_accepted () {
   fi
 }
 
-accept_xcode_eula () {
+accept_xcode_eula() {
   sudo xcodebuild -license accept
 }
 
-setup_xcode () {
+setup_xcode() {
   if ! is_xcode_command_line_tools_installed; then
     log "Installing Xcode Command Line Tools ..."
     install_xcode_command_line_tools
@@ -86,20 +90,20 @@ setup_xcode () {
   fi
 }
 
-is_brew_installed () {
-  if command -v brew >/dev/null; then
+is_brew_installed() {
+  if command -v brew > /dev/null; then
     return 0
   else
     return 1
   fi
 }
 
-install_brew () {
+install_brew() {
   curl -fsS $BREW_INSTALLER | ruby
   export PATH="/usr/local/bin:$PATH"
 }
 
-setup_brew () {
+setup_brew() {
   if [ -d "$BREW_PREFIX" ]; then
     if ! [ -r "$BREW_PREFIX" ]; then
       sudo chown -R "$LOGNAME:admin" "$BREW_PREFIX"
@@ -117,7 +121,7 @@ setup_brew () {
   fi
 }
 
-request_root_privileges () {
+request_root_privileges() {
   log "Requesting root privileges ..."
   sudo -v
 }
diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,45 +1,57 @@
 #!/usr/bin/env bash
-# dotfiles - utility for managing dotfiles
-set -e
+#/ dotfiles – utility for managing dotfiles.
+#/
+#/ Commands:
+#/   -help | -h   displays help and usage.
+#/   -edit        opens "~/.bash_profile" in your editor.
+#/   -upgrade     upgrade to the latest dotfiles release.
+#/   -backup      creates local dotfiles backup.
+
+set -o errexit          # Exit on most errors (see the manual)
+set -o errtrace         # Make sure any error trap is inherited
+set -o nounset          # Disallow expansion of unset variables
+set -o pipefail         # Use last non-zero exit code in a pipeline
+#set -o xtrace          # Trace the execution of the script (debug)
 shopt -s dotglob
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 GITHUB_API_URL='https://api.github.com'
 GITHUB_REPO='nficano/dotfiles'
 
-log () {
+log() {
   # shellcheck disable=SC2059
   printf "$(tput setaf 2)%s$(tput sgr0)\n" "$@"
 }
 
-edit_bash_profile () {
+edit_bash_profile() {
   bash_profile="$(get_dotfiles_prefix)/bash_profile"
   open_file_with_preferred_editor "$bash_profile"
 }
 
-open_file_with_preferred_editor () {
+open_file_with_preferred_editor() {
   ${VISUAL:-${EDITOR:-vim}} $1
 }
 
-get_dotfiles_prefix () {
+get_dotfiles_prefix() {
   fp="$(readlink -f ${0})"
   dir=$(dirname $fp)
   cd $dir || exit 1
   echo "$(git rev-parse --show-toplevel)"
 }
 
-get_latest_version () {
-  repo_tags=$(curl -s  "$GITHUB_API_URL/repos/$GITHUB_REPO/tags")
+get_latest_version() {
+  repo_tags=$(curl -s "$GITHUB_API_URL/repos/$GITHUB_REPO/tags")
   echo "$repo_tags" | grep -Po 'v\d+.\d+.\d+' | head -1
 }
 
-get_path_checksum () {
-  find "$1" -type f -exec md5sum {} \; \
-  | sort -k 2 \
-  | md5sum \
-  | awk '{print $1}'
+get_path_checksum() {
+  find "$1" -type f -exec md5sum {} \; |
+    sort -k 2 |
+    md5sum |
+    awk '{print $1}'
 }
 
-backup_local_dotfiles () {
+backup_local_dotfiles() {
   dotfiles_prefix="$(get_dotfiles_prefix)"
   build_prefix="${TMPDIR-/tmp}/.build"
   backup_prefix="$dotfiles_prefix/.versions/v$DOTFILES_VERSION"
@@ -50,7 +62,7 @@ backup_local_dotfiles () {
   cp -r $dotfiles_prefix/* $build_prefix/
 
   (
-    cd $build_prefix;
+    cd $build_prefix
     zip -ur "backup.zip" ./* -x "*.versions*"
   )
 
@@ -61,14 +73,14 @@ backup_local_dotfiles () {
   log "Backed up $GITHUB_REPO to: $backup_prefix/$checksum.zip"
 }
 
-pull_latest_changes () {
+pull_latest_changes() {
   log "Synchronize local repository with upstream changes ..."
   cd "$(get_dotfiles_prefix)" || exit 1
   git fetch --all
   git reset --hard origin/master
 }
 
-upgrade () {
+upgrade() {
   if is_update_available; then
     latest="$(get_latest_version)"
     log "New version available! (v$DOTFILES_VERSION → $latest)"
@@ -77,14 +89,14 @@ upgrade () {
     pull_latest_changes
     make install
     log "Upgrade completed successfully!"
-    log "Nearly up to date! Run \"reload\" to finish updating."
+    log 'Nearly up to date! Run "reload" to finish updating.'
   else
     log "You're up to date!"
     log "$GITHUB_REPO v$DOTFILES_VERSION is the newest version available."
   fi
 }
 
-is_update_available () {
+is_update_available() {
   latest="$(get_latest_version)"
   version="v$DOTFILES_VERSION"
   if [ "$latest" = "$version" ]; then
@@ -94,41 +106,34 @@ is_update_available () {
   fi
 }
 
-show_usage () {
+show_usage() {
   log "Usage: dotfiles [OPTION]..."
   log "Try 'dotfiles --help' for more information."
 }
 
-show_unknown_command () {
+show_unknown_command() {
   log "ERROR: unknown command \"$1\""
   log "Try 'dotfiles --help' for more information."
+  exit 1
 }
 
-show_help () {
-cat <<EOF
-
-dotfiles – utility for managing dotfiles
-
-Commands:
-  -help|-h            displays help and usage.
-  -edit               opens ``~/.bash_profile`` in your editor.
-  -upgrade            upgrade to the latest dotfiles release.
-  -backup             creates local dotfiles backup.
-EOF
+show_help() {
+  grep '^#/' < "$0" | cut -c4-
+  exit 0
 }
 
-get_commands () {
+get_commands() {
   echo "$(show_help)" | grep -o '\-[a-z]*'
 }
 
 case "$@" in
-  "--help"                 ) show_help; exit 0 ;;
+  "--help"                 ) show_help; ;;
   "-edit"                  ) edit_bash_profile ;;
-  "-listcommands"          ) get_commands; exit 0 ;;
+  "-listcommands"          ) get_commands; ;;
   "-upgrade"               ) upgrade ;;
   "-backup"                ) backup_local_dotfiles ;;
-  "-h"                     ) show_help; exit 0 ;;
-  ""                       ) show_usage; exit 0 ;;
-  *                        ) show_unknown_command "$@"; exit 1 ;;
+  "-h"                     ) show_help ;;
+  ""                       ) show_usage ;;
+  *                        ) show_unknown_command "$@" ;;
 esac
 exit 0
diff --git a/bin/network b/bin/network
--- a/bin/network
+++ b/bin/network
@@ -1,126 +1,167 @@
 #!/usr/bin/env bash
-# network - utility for gathering information about your local network.
-set -e
+#/ network – utility for gathering information about your local network.
+#/
+#/ Commands:
+#/   -getlanhosts                discover all devices on your network.
+#/   -getgatewayip               displays the address of your "network
+#/                               gateway",
+#/                               or the edge device (ie: router) that sits
+#/                               between you and another network (ie: the
+#/                               Internet).
+#/   -gethostip                  displays your host ip address
+#/   -getmodemip                 attempts to find the ip address of your modem
+#/                               (first hop after your router/gateway).
+#/   -getnetworkip               the common prefix of your private ip address,
+#/                               used to refer to your subnet as a whole.
+#/   -getprivateip               alias to "ip host"
+#/   -getpublicip                the globally unique address assigned to your
+#/                               network by your isp
+#/   -getroutingtable            display your routing table.
+#/   -getarptable                display your address resolution protocol (arp)
+#/                               table.
+#/   -getrouterip                alias to "ip gateway"
+#/   -getispname                 displays the name of your isp
+#/   -probe <modem|router>       attempts to identify the operating system, open
+#/                               ports, and running software on your modem or
+#/                               router.
+#/   -exploitscan [target]       runs an advanced vulnerability scan against your
+#/                               current subnet (or target ip if provided).
+#/   -osscan [target]            runs an *aggressive* operating system/version
+#/                               detection scan against your current subnet (or
+#/                               target ip if provided).
+#/   -snmpscan [target]          runs a simple network management protocol (snmp)
+#/                               scan against your current subnet (or target ip if
+#/                               provided).
+#/   -webconfig <modem|router>   opens the web config for your modem or router.
+#/   -getsubnet [-o <bit|hex>]   displays your host subnet mask address ip.
+#/   -help|-h                    displays help and usage.
 
-get_arp_table () {
+set -o errexit          # Exit on most errors (see the manual)
+set -o errtrace         # Make sure any error trap is inherited
+set -o nounset          # Disallow expansion of unset variables
+set -o pipefail         # Use last non-zero exit code in a pipeline
+#set -o xtrace          # Trace the execution of the script (debug)
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
+get_arp_table() {
   arp -al | awk '{printf "%-35s %-20s %-5s \n", $1, $2, $4}'
 }
 
-get_isp_name () {
-  whois "$(get_public_ip_address)" \
-  | grep OrgName \
-  | awk '{$1="";print}' \
-  | xargs
+get_isp_name() {
+  whois "$(get_public_ip_address)" |
+    grep OrgName |
+    awk '{$1="";print}' |
+    xargs
 }
 
-get_public_ip_address () {
+get_public_ip_address() {
   echo "$(curl -s "https://api.ipify.org/")"
 }
 
-get_host_ip_address () {
-  ifconfig \
-  | egrep 'inet\s(192|172|10)' \
-  | awk '{print $2}'
+get_host_ip_address() {
+  ifconfig |
+    egrep 'inet\s(192|172|10)' |
+    awk '{print $2}'
 }
 
-get_routing_table () {
+get_routing_table() {
   netstat -nr -f inet
 }
 
-get_network_ip_address () {
-  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" \
-  | grep "Network address" \
-  | awk '{print $4}'
+get_network_ip_address() {
+  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" |
+    grep "Network address" |
+    awk '{print $4}'
 }
 
-get_network_mask () {
-  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" \
-  | grep "Network mask" \
-  | awk '{print $4}' \
-  | egrep -o '([0-9]{1,3}[.]){3}[0-9]{1,3}'
+get_network_mask() {
+  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" |
+    grep "Network mask" |
+    awk '{print $4}' |
+    egrep -o '([0-9]{1,3}[.]){3}[0-9]{1,3}'
 }
 
-get_network_mask_bits () {
-  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" \
-  | grep "Network mask (bits)" \
-  | awk '{print $5}'
+get_network_mask_bits() {
+  sipcalc "$(get_host_ip_address)" "$(get_network_mask_hex)" |
+    grep "Network mask (bits)" |
+    awk '{print $5}'
 }
 
-get_network_mask_hex () {
-  ifconfig \
-  | egrep 'inet\s(192|172|10)' \
-  | awk '{print $4}'
+get_network_mask_hex() {
+  ifconfig |
+    egrep 'inet\s(192|172|10)' |
+    awk '{print $4}'
 }
 
-get_gateway_ip_address () {
-  netstat -rn \
-  | egrep 'default\s+(192|172|10)' \
-  | awk '{print $2}'
+get_gateway_ip_address() {
+  netstat -rn |
+    egrep 'default\s+(192|172|10)' |
+    awk '{print $2}'
 }
 
-lan_host_discovery () {
-  sudo nmap "$(get_network_ip_address)/$(get_network_mask_bits)" -sP -oG - \
-  | grep Host \
-  | awk '{print $2 "\t" $3}' \
-  | sort
+lan_host_discovery() {
+  sudo nmap "$(get_network_ip_address)/$(get_network_mask_bits)" -sP -oG - |
+    grep Host |
+    awk '{print $2 "\t" $3}' |
+    sort
 }
 
-get_modem_ip_address () {
+get_modem_ip_address() {
   sudo nmap \
-  -sS 192.168.100.1 192.168.0.1 10.0.0.1 10.1.10.1 \
-  --min-parallelism 100 |
-  egrep -o '([0-9]{1,3}[.]){3}[0-9]{1,3}'
+    -sS 192.168.100.1 192.168.0.1 10.0.0.1 10.1.10.1 \
+    --min-parallelism 100 |
+    egrep -o '([0-9]{1,3}[.]){3}[0-9]{1,3}'
 }
 
-open_router_config () {
+open_router_config() {
   python -mwebbrowser "http://$(get_gateway_ip_address)"
 }
 
-open_modem_config () {
+open_modem_config() {
   python -mwebbrowser "http://$(get_modem_ip_address)"
 }
 
-probe_modem () {
+probe_modem() {
   sudo nmap \
-  --min-parallelism 100 \
-  -A \
-  -T4 "$(get_modem_ip_address)"
+    --min-parallelism 100 \
+    -A \
+    -T4 "$(get_modem_ip_address)"
 }
 
-probe_router () {
+probe_router() {
   sudo nmap \
-  --min-parallelism 100 \
-  -A \
-  -T4 "$(get_gateway_ip_address)"
+    --min-parallelism 100 \
+    -A \
+    -T4 "$(get_gateway_ip_address)"
 }
 
-exploit_scan () {
+exploit_scan() {
   if ! is_vulscan_installed || ! is_nmap_vulners_installed; then
     install_nmap_scripts
   fi
   sudo nmap \
-  --script nmap-vulners,vulscan \
-  --script-args vulscandb=scipvuldb.csv \
-  -sV "$(get_target "$1")"
+    --script nmap-vulners,vulscan \
+    --script-args vulscandb=scipvuldb.csv \
+    -sV "$(get_target "$1")"
 }
 
-os_scan () {
+os_scan() {
   sudo nmap \
-  --min-parallelism 100 \
-  -A \
-  -Pn \
-  -T4 "$(get_target "$1")"
+    --min-parallelism 100 \
+    -A \
+    -Pn \
+    -T4 "$(get_target "$1")"
 }
 
-snmp_scan () {
+snmp_scan() {
   sudo nmap \
-  --script snmp-brute,snmp-info \
-  --script-args snmplist=community.lst \
-  -sU -p161 \
-   "$(get_target "$1")"
+    --script snmp-brute,snmp-info \
+    --script-args snmplist=community.lst \
+    -sU -p161 \
+    "$(get_target "$1")"
 }
 
-get_target () {
+get_target() {
   if [ -z "$1" ]; then
     echo "$(get_network_ip_address)/$(get_network_mask_bits)"
   else
@@ -128,103 +169,71 @@ get_target () {
   fi
 }
 
-show_usage () {
+show_usage() {
   echo "Usage: network [OPTION]..."
   echo "Try 'network --help' for more information."
 }
 
-show_unknown_command () {
+show_unknown_command() {
   echo "ERROR: unknown command \"$1\""
   echo "Try 'network --help' for more information."
+  exit 1
 }
 
-get_commands () {
+get_commands() {
   echo "$(show_help)" | grep -o '\-[a-z]*'
+  exit 0
 }
 
-get_nmap_script_path () {
+get_nmap_script_path() {
   dirname "$(find /usr/local -type f -name '*.nse' -print | head -n 1)"
 }
 
-is_nmap_vulners_installed () {
+is_nmap_vulners_installed() {
   [[ -d "$(get_nmap_script_path)/nmap-vulners" ]]
 }
 
-is_vulscan_installed () {
+is_vulscan_installed() {
   [[ -d "$(get_nmap_script_path)/vulscan" ]]
 }
 
-install_nmap_vulners () {
+install_nmap_vulners() {
   cd "$(get_nmap_script_path)" || exit 1
   git clone https://github.com/vulnersCom/nmap-vulners.git
 }
 
-install_vulscan () {
+install_vulscan() {
   cd "$(get_nmap_script_path)" || exit 1
   git clone https://github.com/scipag/vulscan.git
 }
 
-update_vulscan () {
+update_vulscan() {
   cd "$(get_nmap_script_path)/vulscan/utilities/updater" || exit 1
   chmod +x "$(get_nmap_script_path)/vulscan/utilities/updater/updateFiles.sh"
   "$(get_nmap_script_path)/vulscan/utilities/updater/updateFiles.sh"
 }
 
-install_nmap_scripts () {
+install_nmap_scripts() {
   install_nmap_vulners
   install_vulscan
   update_vulscan
 }
 
-contains () {
+contains() {
   local -r haystack="$1"
   local -r needle="$2"
 
-  [[ "$haystack" == *"$needle"* ]]
+  [[ $haystack == *"$needle"* ]]
 }
 
-show_help () {
-cat <<EOF
-
-network – utility for gathering information about your local network.
-
-Commands:
-  -getlanhosts                discover all devices on your network.
-  -getgatewayip               displays the address of your "network gateway",
-                              or the edge device (ie: router) that sits
-                              between you and another network (ie: the
-                              Internet).
-  -gethostip                  displays your host ip address
-  -getmodemip                 attempts to find the ip address of your modem
-                              (first hop after your router/gateway).
-  -getnetworkip               the common prefix of your private ip address,
-                              used to refer to your subnet as a whole.
-  -getprivateip               alias to "ip host"
-  -getpublicip                the globally unique address assigned to your
-                              network by your isp
-  -getroutingtable            display your routing table.
-  -getarptable                display your address resolution protocol (arp)
-                              table.
-  -getrouterip                alias to "ip gateway"
-  -getispname                 displays the name of your isp
-  -probe <modem|router>       attempts to identify the operating system, open
-                              ports, and running software on your modem or
-                              router.
-  -exploitscan [target]       runs an advanced vulnerability scan against your
-                              current subnet (or target ip if provided).
-  -osscan [target]            runs an *aggressive* operating system/version
-                              detection scan against your current subnet (or
-                              target ip if provided).
-  -snmpscan [target]          runs a simple network management protocol (snmp) 
-                              scan against your current subnet (or target ip if
-                              provided).
-  -webconfig <modem|router>   opens the web config for your modem or router.
-  -getsubnet [-o <bit|hex>]   displays your host subnet mask address ip.
-  -help|-h                    displays help and usage.
-EOF
+show_help() {
+  grep '^#/' < "$0" | cut -c4-
+  exit 0
 }
 
-if [ ! -x "$(command -v nmap)" ] || [ ! -x "$(command -v sipcalc)" ] || [ ! -x "$(command -v egrep)" ]; then
+if [ ! -x "$(command -v nmap)" ] ||
+   [ ! -x "$(command -v sipcalc)" ] ||
+   [ ! -x "$(command -v egrep)" ]; then
   echo "Error: 'nmap', 'sipcalc', and 'egrep' must first be installed."
   echo "To fix, try running: brew install nmap sipcalc egrep"
   exit 1
@@ -253,10 +262,10 @@ case "$@" in
   "-updatevulscan"         ) update_vulscan ;;
   "-webconfig modem"       ) open_modem_config ;;
   "-webconfig router"      ) open_router_config ;;
-  "listcommands"           ) get_commands; exit 0 ;;
-  "--help"                 ) show_help; exit 0 ;;
-  "-h"                     ) show_help; exit 0 ;;
-  ""                       ) show_usage; exit 0 ;;
-  *                        ) show_unknown_command "$@"; exit 1 ;;
+  "listcommands"           ) get_commands ;;
+  "--help"                 ) show_help ;;
+  "-h"                     ) show_help ;;
+  ""                       ) show_usage ;;
+  *                        ) show_unknown_command "$@" ;;
 esac
 exit 0
