added upgrade to dots

diff --git a/bin/dots b/bin/dots
--- a/bin/dots
+++ b/bin/dots
@@ -1,9 +1,21 @@
 #!/usr/bin/env bash
 # dots - utility for managing dotfiles
 set -e
+GITHUB_API_URL='https://api.github.com'
+GITHUB_REPO='nficano/dotfiles'
+
+silence () {
+  "$@" 2> /dev/null > /dev/null;
+}
+
+log () {
+  message="$1"; shift
+  # shellcheck disable=SC2059
+  printf "$message\n" "$@"
+}
 
 edit_bash_profile () {
-  bash_profile="$(get_dotfiles_path)/bash_profile"
+  bash_profile="$(get_dotfiles_prefix)/bash_profile"
   open_file_with_preferred_editor "$bash_profile"
 }
 
@@ -11,7 +23,7 @@ open_file_with_preferred_editor () {
   ${VISUAL:-${EDITOR:-vim}} $1
 }
 
-get_dotfiles_path () {
+get_dotfiles_prefix () {
   fp="$(readlink -f ${0})"
   dir=$(dirname $fp)
   cd $dir || exit 1
@@ -19,28 +31,82 @@ get_dotfiles_path () {
 }
 
 show_usage () {
-  echo "Usage: dots [OPTION]..."
-  echo "Try 'dots --help' for more information."
+  log "Usage: dots [OPTION]..."
+  log "Try 'dots --help' for more information."
 }
 
 show_unknown_command () {
-  echo "ERROR: unknown command \"$1\""
-  echo "Try 'dots --help' for more information."
+  log "ERROR: unknown command \"$1\""
+  log "Try 'dots --help' for more information."
+}
+
+get_repo_tags () {
+  curl -s  "$GITHUB_API_URL/repos/$GITHUB_REPO/tags"
 }
 
 get_latest_version () {
-  curl -s https://api.github.com/repos/nficano/dotfiles/tags | jq -r '.[0].name'
+  echo "$(get_repo_tags)" | jq -r '.[0].name'
+}
+
+get_path_checksum () {
+  find "$1" -type f -exec md5sum {} \; | sort -k 2 | md5sum  | awk '{print $1}'
+}
+
+get_file_checksum () {
+  md5sum "$1" | awk '{print $1}'
+}
+
+backup () {
+  dotfiles_prefix="$(get_dotfiles_prefix)"
+  build_prefix="$TMPDIR/.build"
+  backup_prefix="$dotfiles_prefix/.versions/v$DOTFILES_VERSION"
+
+  mkdir -p $backup_prefix
+  mkdir -p $build_prefix
+
+  cp -R $dotfiles_prefix/* $build_prefix/
+
+  (
+    cd $build_prefix;
+    silence zip -ur "backup.zip" ./* -x "*.versions*" -x "*.git*"
+  )
+
+  mv "$build_prefix/backup.zip" "$backup_prefix/backup.zip"
+  checksum="$(get_path_checksum "$build_prefix")"
+  mv "$backup_prefix/backup.zip" "$backup_prefix/$checksum.zip"
+  rm -rf $build_prefix
+}
+
+upgrade () {
+  if is_update_available; then
+    backup
+    cd "$(get_dotfiles_prefix)" || exit 1
+    git fetch --all
+    git reset --hard origin/master
+  else
+    log "%s" "You're up-to-date!" \
+      "nficano/dotfiles v$DOTFILES_VERSION is the newest version available."
+  fi
+}
+
+is_update_available () {
+  latest="$(get_latest_version)"
+  version="v$DOTFILES_VERSION"
+  if [ "$latest" = "$version" ]; then
+    return 1
+  else
+    return 0
+  fi
 }
 
 check_for_updates () {
-  latest="$(get_latest_version)"
-  installed="v$DOTFILES_VERSION"
-  if [ "$latest" = "$installed" ]; then
-    echo "You're up-to-date! -" \
-     "nficano/dotfiles $installed is the newest version available."
+  if ! is_update_available; then
+    log "%s" "You're up-to-date!" \
+      "nficano/dotfiles v$DOTFILES_VERSION is the newest version available."
   else
-    echo "New version available! -" \
-      "nficano/dotfiles $latest is ready to be installed (current $installed)."
+    log "%s" "New version available!" \
+      "nficano/dotfiles $(get_latest_version) is ready to be version " \
+      "(current v$DOTFILES_VERSION)."
   fi
 }
 
@@ -50,9 +116,11 @@ cat <<EOF
 dots – utility for managing dotfiles
 
 Commands:
-  -help|-h          displays help and usage.
-  -editprofile      opens bash_profile in your preferred editor.
-  -checkforupdates  checks if your dotfiles are up-to-date.
+  -help|-h            displays help and usage.
+  -editprofile        opens bash_profile in your editor.
+  -checkforupdates    checks if your dotfiles is the latest version.
+  -upgrade            upgrades your dotfiles to latest version.
+  -backup             makes a copy of your current dotfiles.
 EOF
 }
 
@@ -61,10 +129,12 @@ get_commands () {
 }
 
 case "$@" in
-  "-editprofile"           ) edit_bash_profile ;;
   "--help"                 ) show_help; exit 0 ;;
   "-checkforupdates"       ) check_for_updates ;;
+  "-editprofile"           ) edit_bash_profile ;;
   "-listcommands"          ) get_commands; exit 0 ;;
+  "-upgrade"               ) upgrade ;;
+  "-backup"                ) backup ;;
   "-h"                     ) show_help; exit 0 ;;
   ""                       ) show_usage; exit 0 ;;
   *                        ) show_unknown_command "$@"; exit 1 ;;
