Remove misc directory

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,8 +1,8 @@
 #!/bin/bash
-set -o errexit          # Exit on most errors (see the manual)
-set -o errtrace         # Make sure any error trap is inherited
-set -o nounset          # Disallow expansion of unset variables
-set -o pipefail         # Use last non-zero exit code in a pipeline
+set -o errexit  # Exit on most errors (see the manual)
+set -o errtrace # Make sure any error trap is inherited
+set -o nounset  # Disallow expansion of unset variables
+set -o pipefail # Use last non-zero exit code in a pipeline
 #set -o xtrace          # Trace the execution of the script (debug)
 export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
@@ -45,7 +45,7 @@ get_brewfile_path() {
 }
 
 is_duti_installed() {
-  if command -v duti > /dev/null; then
+  if command -v duti >/dev/null; then
     return 0
   else
     return 1
@@ -71,7 +71,7 @@ install_formulaes_from_brewfile() {
 }
 
 is_xcode_command_line_tools_installed() {
-  if xcode-select -p > /dev/null; then
+  if xcode-select -p >/dev/null; then
     return 0
   else
     return 1
@@ -79,8 +79,8 @@ is_xcode_command_line_tools_installed() {
 }
 
 install_xcode_command_line_tools() {
-  xcode-select --install > /dev/null
-  until xcode-select -p > /dev/null; do
+  xcode-select --install >/dev/null
+  until xcode-select -p >/dev/null; do
     sleep 5
   done
 }
@@ -114,7 +114,7 @@ setup_xcode() {
 }
 
 is_brew_installed() {
-  if command -v brew > /dev/null; then
+  if command -v brew >/dev/null; then
     return 0
   else
     return 1
@@ -182,7 +182,9 @@ setup_default_file_associations() {
   duti -s com.microsoft.VSCode .yml all
   duti -s com.microsoft.VSCode .toml all
   duti -s com.microsoft.VSCode .jsonl all
-
+  duti -s com.microsoft.VSCode .plist all
+  duti -s com.microsoft.VSCode .scpt all
+  duti -s com.microsoft.VSCode Makefile all
 
   duti -s com.microsoft.VSCode public.json all
   duti -s com.microsoft.VSCode public.plain-text all
